### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by MikeNGarrett** [sutrofm/sutrofm#138]
Upon authorizing for the first time (yay new users!) the following is output on the page: 
__You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page__

"AuthCanceled at /auth/complete/rdio-oauth2/
Authentication process canceled
Request Method:	GET
Request URL:	http://rdioparty.com/auth/complete/rdio-oauth2/?redirect_state=ApI7C2Phwr3qUYn0LoiUeaJBZqs18SHt&state=ApI7C2Phwr3qUYn0LoiUeaJBZqs18SHt&code=eA-7-XtCrh1W-4Z2zn1hqA
Django Version:	1.5
Exception Type:	AuthCanceled
Exception Value:	
Authentication process canceled
Exception Location:	/usr/local/lib/python2.7/dist-packages/social_auth/backends/__init__.py in auth_complete, line 827
Python Executable:	/usr/bin/uwsgi
Python Version:	2.7.6
Python Path:	
['.',
 '',
 '/usr/local/lib/python2.7/dist-packages/uWSGI-2.0.8-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pip-6.0.6-py2.7.egg',
 '/opt/rdioparty',
 '/opt/rdioparty/rdiodj',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/dist-packages/rdioapi',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7/dist-packages']
Server time:	Mon, 18 May 2015 08:17:11 -0700"

**Comment by BCWilsonDotCom** [comment]
I’ve set DEBUG=False in Prod.

**Comment by jackdbernier** [comment]
Solved right ?
