### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by dasevilla** [sutrofm/sutrofm#140]
Let's rename the project to *Shindig for Rdio* to comply with the API terms.

**Comment by MikeNGarrett** [comment]
Shindig?

Can I make some suggestions or is shindig for rdio set in stone?

**Comment by BCWilsonDotCom** [comment]
Absolutely.

**Comment by dasevilla** [comment]
Yes, we're open to other name suggestions

**Comment by MikeNGarrett** [comment]
Here's what I've come up with so far: 
MixSet - Where your tastes mix with other music lovers.
MusicMerge - Come together. Share your songs.
Q - Cue tracks to the Q.
PopTrack - Vote on what plays next.

Each of these names cover a different perspective on the app. They each imply different directions which should indicate the intention of the product. Which aspect of Rdio Party is the most important from your perspective? Sharing tracks, collaborating on playlists, promoting music, or giving the power to choose to the people? A name will be stronger if you can narrow the scope down to the most important aspect, whether it be one of these names or another.

**Comment by superemily** [comment]
Studio Dog - Inspired Music
![studio_dog](https://cloud.githubusercontent.com/assets/1606994/7739053/4e972568-ff10-11e4-9aca-37c1d6cd2b2d.jpg)
Brought to you by our mascot, "Shindigly"

**Comment by mkapolka** [comment]
I like the name Shindigly. It is fun to say out loud.

**Comment by rstecker** [comment]
Since Brandon is the one actually putting up $$ so far, I think he should get final say/more say. 

Am not fond of Shindigly. I liked the idea of "Studio Dog," as discussed over lunch because anything that uses real-words is good in my book.  I also like:
- MixSet
- MusicMerge

I will now remove myself from further voting/opinions. Ya'll should fight this out and we should rename things next Tuesday (2/26) over lunch.

**Comment by Saidhbh** [comment]
I am also giving a vote towards Shindig.ly. Also, I thought Marek has paid for that domain already...no...?
I am against anything with "Dog" in the name... :-1:

**Comment by gabek** [comment]
I don't hate Shindig as a product name and Shindig.ly as a domain, but I hate Shindigly as a product name.

**Comment by Saidhbh** [comment]
^^ I agree Gabe

**Comment by MikeNGarrett** [comment]
Love the dog. That's a great shot.

**Comment by jackdbernier** [comment]
Hate is such a strong word! 

Beets Party
MusicCat
Musicpack
DogJay
Partify
MusicRail - all on the same track


Most of these names are totally lame. I like - love - shindig.ly

Shindig - more then music. Parties tuned by you

**Comment by MikeNGarrett** [comment]
Read this before you agree to shindig
http://www.worldwidewords.org/qa/qa-shi4.htm

That's the last I'll say on the matter of shindigly. ;-)

**Comment by superstrong** [comment]
party for rdio
pardio
pard.io

**Comment by MikeNGarrett** [comment]
Doesn't that violate the T&C of the API?

**Comment by superstrong** [comment]
Yeah, just skimmed the TOS and you're right. 

Turntable for rdio (turntable.io looks free)

**Comment by MikeNGarrett** [comment]
Now that would get some press! Haha.

**Comment by MikeNGarrett** [comment]
@BCWilsonDotCom What's the verdict? Did you get a chance to talk about it?

**Comment by superemily** [comment]
There has been no verdict yet. I am submitting the name sutro.fm for consideration.

**Comment by yckmd** [comment]
Not huge on Shindig. turntable.io is pretty great, haha. 

Thought of mixr, but I guess there are Beats Headphones that use this? Trackly? MixSet is OK too

**Comment by dasevilla** [comment]
The team decided on sutro.fm (always lowercase) as nod to [Sutro Tower](http://en.wikipedia.org/wiki/Sutro_Tower) and radio.
