### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by dasevilla** [sutrofm/sutrofm#150]
We need a new logo for the new name

**Comment by MikeNGarrett** [comment]
![sutro.fm](https://cloud.githubusercontent.com/assets/394888/7884665/75a36b2e-05ed-11e5-858f-1d1050373fad.jpg)

This mark act as a simple representation of the tower antennas without representing the tower explicitly. The relative size and spacing of the lines of the mark mirror a three dimensional rendering of the antennas in space. 

The spacing and growth of the lines out from the center indicates a broadcast while the number of lines also represents a group of listeners. 

The type is strong and bold to match the weight of the lines with tight tracking that makes the logotype stand on its own. The dot between 'sutro' and 'fm' stands out as a reference back to the mark. 

Colors were inspired by the tower, itself. Going with this palette will not leave any doubt that this is a Rdio-powered product and not a Rdio product. I'm not sure if this is what you're going for, but I decided to run with it. 

Cheers!

**Comment by jozecuervo** [comment]
Fantastic concept!

**Comment by rstecker** [comment]
wooaaaaah... 
that's some serious quality marketing speak there ;)  I'm sold. I think we should use that exactly as-is

**Comment by dasevilla** [comment]
Love it! Can you create a pull request making it official? Also, could we get a square version for the Twitter account?

**Comment by phrenchphry11** [comment]
Oh wait let me try uploading this one to the Twitter account!  I think it might work!  Love this new logo.

**Comment by MikeNGarrett** [comment]
Out of pocket right now. Glad you all like it. I'll clean it up and generate the right versions and commit them. Do we need a version on black?

Also, the typeface is avenir next. Should we incorporate that into the site design?

**Comment by MikeNGarrett** [comment]
I didn't have a chance to actually check this into the repo in the appropriate place yet. Here all the different versions of icons. I have 2 twitter icons, a twitter bg, favicons, web logo and some source files, including the vector source. 

Have fun. 
http://the.digitalflan.com/ba77

![sutro-twitter-icon-dark](https://cloud.githubusercontent.com/assets/394888/7951832/76e5548a-097a-11e5-9353-82319eee0496.jpg)

**Comment by phrenchphry11** [comment]
awesome!  updated the twitter account with the new icons.

**Comment by gabek** [comment]
Fancypants.
