### ISSUE TITLE
Always Skipping to next song. 

### ISSUE THREAD

**Issue by FreeForm-Radio** [sutrofm/sutrofm#163]
I'm guessing this is related to the rdio update. 

This morning when I went to start adding songs to the queue, it would immediately begin playing the ones that were added instead of waiting for the current song to end. 

Everything seemed to be working yesterday after the fix was put into place. We already had songs in the queue, but they were playing normally and we added some without any trouble. 

Thanks,

Alan

**Comment by FreeForm-Radio** [comment]
accidentally hit the close button.

**Comment by rstecker** [comment]
Just checked and the bug is still happening.  We'll hopefully get a fix some time early this week.

Really sorry, there is a backend re-write going on that should make everything much better... but isn't done yet.

**Comment by FreeForm-Radio** [comment]
Hi Rebecca,

No problem at all. I develop software and understand very well how things
take longer than one expects. We're having fun being the beta-testers. :-)

It will be great when the new backend is ready though. I'm sure it will
result in many more people using the party site!!

Thanks for the reply!!

Alan

**Comment by mkapolka** [comment]
IT IS DONE

**Comment by FreeForm-Radio** [comment]
We noticed that a few minutes ago. Thanks from all of us!!! We'll give it a
good test tomorrow.
