### ISSUE TITLE
Usernames / icons not appearing in chat

### ISSUE THREAD

**Issue by mkapolka** [sutrofm/sutrofm#172]
Chat pulls from an internal list of users to get details re: username, icon. Probably we are not sending down the right information from the backend (filtering on inactive users?)

<img width="324" alt="screen shot 2015-09-21 at 3 30 21 pm" src="https://cloud.githubusercontent.com/assets/3412796/10006841/9043bb68-6075-11e5-9385-793b90381492.png">

**Comment by jackdbernier** [comment]
I believe this is fixed with https://github.com/sutrofm/sutrofm/pull/174
